# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import QAction, QTextEdit, QMainWindow, QApplication, QFileDialog, QWidget, QPushButton
# from utils import sniper
from utils import snipe_price


class SniperWindow(object):
    def __init__(self):
        self.current_file_name = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 547)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open = QPushButton(self.centralwidget)
        self.open.setGeometry(QtCore.QRect(60, 490, 113, 32))
        self.open.setObjectName("open")
        self.open.clicked.connect(self.file_open)
        self.save = QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(200, 490, 113, 32))
        self.save.setObjectName("save")
        self.save.clicked.connect(self.file_save)
        self.snipe = QPushButton(self.centralwidget)
        self.snipe.setGeometry(QtCore.QRect(340, 490, 113, 32))
        self.snipe.setObjectName("snipe")
        self.snipe.clicked.connect(self.sniper_action)
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(30, 30, 761, 441))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        openFile = QAction("&Open", MainWindow)
        openFile.setShortcut("Ctrl+O")
        openFile.setStatusTip('Open file')
        openFile.triggered.connect(self.file_open)

        saveFile = QAction("&Save", MainWindow)
        saveFile.setShortcut("Ctrl+S")
        saveFile.setStatusTip('Save')
        saveFile.triggered.connect(self.file_save)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open.setText(_translate("MainWindow", "open"))
        self.snipe.setText(_translate("MainWindow", "snipe"))
        self.save.setText(_translate("MainWindow", "save"))

    def file_open(self):
        file_name, _ = QFileDialog.getOpenFileName(None, 'Open File', '.', 'Text files (*.txt);;All Files (*)')
        if file_name:
            with open(file_name, 'r') as file:
                text = file.read()
            self.textEdit.setPlainText(text)
            self.current_file_name = file_name

    def file_save(self):
        if self.current_file_name:
            name = self.current_file_name
        else:
            name, _ = QFileDialog.getSaveFileName(None, 'Save File', '.', 'Text files (*.txt);;All Files (*)')
        if name:
            with open(name, 'w', encoding='utf-8') as file:
                text = self.textEdit.toPlainText()
                file.write(text)
            self.current_file_name = name

    def sniper_action(self):
        snipe_price()
        if self.current_file_name:
            file_name = self.current_file_name
            if file_name:
                with open(file_name, 'r') as file:
                    text = file.read()
                self.textEdit.setPlainText(text)
                self.current_file_name = file_name


if __name__ == "__main__":
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = SniperWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
